### ISSUE TITLE
添加这个插件之后导致@vuepress/medium-zoom插件无效

### ISSUE THREAD

**Issue by Gitsifu** [moefyit/vuepress-plugin-cursor-effects#1]

**Comment by SigureMo** [comment]
请提供复现的 repo，请确定是该插件的问题，因为我的博客同时使用这两个插件并没有任何问题

**Comment by Gitsifu** [comment]
> 请提供复现的 repo，请确定是该插件的问题，因为我的博客同时使用这两个插件并没有任何问题

https://github.com/Gitsifu/Gitsifu.github.io.src

**Comment by SigureMo** [comment]
有效，仍然可以用，与本插件无关。
